ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - dprint
  - sharp
  - nuxt-bun-compile

overrides:
  minimatch@<10.2.1: '>=10.2.1'
